// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4UIqzK9SFAjgwYrJu4If2I_HT1BOBcxA',
    appId: '1:1018045268341:web:362249e7eb010362c0d33c',
    messagingSenderId: '1018045268341',
    projectId: 'vinflow-e82bd',
    authDomain: 'vinflow-e82bd.firebaseapp.com',
    storageBucket: 'vinflow-e82bd.firebasestorage.app',
    measurementId: 'G-JH0QGHDG83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKK36FJDIuuPs6w76b39NzZuo3eejhkkY',
    appId: '1:1018045268341:android:8be667ecb56cc3b7c0d33c',
    messagingSenderId: '1018045268341',
    projectId: 'vinflow-e82bd',
    storageBucket: 'vinflow-e82bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYoMbpHXJcykarN36CR1Y2nXsFSfHk31A',
    appId: '1:1018045268341:ios:0b1c911908b94220c0d33c',
    messagingSenderId: '1018045268341',
    projectId: 'vinflow-e82bd',
    storageBucket: 'vinflow-e82bd.firebasestorage.app',
    iosBundleId: 'com.example.vinflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYoMbpHXJcykarN36CR1Y2nXsFSfHk31A',
    appId: '1:1018045268341:ios:0b1c911908b94220c0d33c',
    messagingSenderId: '1018045268341',
    projectId: 'vinflow-e82bd',
    storageBucket: 'vinflow-e82bd.firebasestorage.app',
    iosBundleId: 'com.example.vinflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4UIqzK9SFAjgwYrJu4If2I_HT1BOBcxA',
    appId: '1:1018045268341:web:9ebe6186fe481707c0d33c',
    messagingSenderId: '1018045268341',
    projectId: 'vinflow-e82bd',
    authDomain: 'vinflow-e82bd.firebaseapp.com',
    storageBucket: 'vinflow-e82bd.firebasestorage.app',
    measurementId: 'G-SPWHJ7M5WE',
  );
}
