name: Deploy VinFlow to GitHub Pages

on:
  push:
    branches:
      - main # Akan jalan otomatis setiap kamu push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Web
        run: |
          flutter pub get
          # PERBAIKAN: Menghapus --web-renderer karena versi Flutter terbaru sudah menanganinya secara internal
          # Kita tetap pakai --no-tree-shake-icons agar ikon di PocketProvider tidak error
          flutter build web --release --base-href "/${{ github.event.repository.name }}/" --no-tree-shake-icons

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages # Hasil build akan dikirim ke branch ini